#! /bin/sh
#
MONITORES=$(xrandr --query | grep " connected" | grep -vc '^$')

if [ $MONITORES = 2 ]; then
    xrandr --output HDMI-1 --auto --left-of eDP-1 &
    bspc monitor HDMI-1 -d I II III IV V VI
    bspc monitor eDP-1 -d VII VIII IX X
    setxkbmap -layout us -variant altgr-intl &
    echo "us" > /tmp/current_kb
else
    bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
    setxkbmap -layout latam &
    echo "latam" > /tmp/current_kb
fi

#bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc config pointer_follows_focus true
# bspc config focus_follows_pointer true

# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

#
# Autostart
#
pgrep -x sxhkd > /dev/null || sxhkd &

# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
# Picom
# picom -b &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

