#! /bin/sh

MONITORES=$(xrandr --query | grep " connected" | grep -vc '^$')

# Autostart
sxhkd &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
nitrogen --restore &
sleep 1 &
picom -b &
nm-applet --indicator &
xautolock -time 10 -locker blurlock &
~/.config/polybar/launch.sh &
dunst &
~/.config/bspwm/scripts/low_bat_notifier.sh

if [ $MONITORES == 2 ]; then
	xrandr --output HDMI-1 --auto --left-of eDP-1 &
	bspc monitor HDMI-1 -d 1 2 3 4 5 6
	bspc monitor eDP-1 -d 7 8 9 0
	setxkbmap -layout us -variant altgr-intl &
	echo "us" >/tmp/current_kb
else
	bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0
	setxkbmap -layout latam &
	echo "latam" >/tmp/current_kb
fi

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# bspc config pointer_follows_focus true
# bspc config focus_follows_pointer true

# Border
bspc config focused_border_color "#6c71c4"
bspc config normal_border_color "#073642"
bspc config active_border_color "#073642"
