#!/bin/bash

WINDOW_ID_OPTIONS=/tmp/window_id_options

launch() {
    sleep 0.2
    killall polybar
    polybar panel &
    BAR_ID=$!
    sleep 0.2
    polybar top &
    BAR_ID=$!
}

rofi_open() {
    options_close
    rofi -show run -location 0 -width 2408 -padding 700 -lines 10
}

search_open() {
    rofi -show window -location 1
}

menu_options() {
	echo -e "\tpower"
	echo -e "\treboot"
	echo -e "\tLock"
	echo -e "\tLogout"
	echo -e "鈴\tsuspend"
    echo -e "\tScreenshot"
    echo -e "\tstacked"
    echo -e "ﬓ\ttabbed"
    echo -e "\tsplit"
	echo -e "\tprev"
	echo -e "\tstop"
	echo -e "\tnext"
	echo -e "\tplay"
	echo -e "凌\trepeat"
	echo -e "\trandom"

}

menu_selection() {
	case "$2" in
	    prev)
            mpc -q prev
            ;;
        play)
            mpc -q toggle
            ;;
        stop)
            mpc -q stop
            ;;
        next)
            mpc -q next
            ;;
        repeat)
            mpc -q repeat
            ;;
        random)
            mpc -q random
            ;;
	    poweroff)
            systemctl poweroff
            ;;
        reboot)
            systemctl reboot
            ;;
		Lock)
			i3lock
			;;
		Logout)
			i3-msg exit
			;;
	    suspend)
			mpc -q pause
            amixer set Master mute
            systemctl suspend
			;;
        Screenshot)
            exec scrot -e 'feh $f -x' --delay 1 &
			;;
		tabbed)
			i3-msg layout tabbed
			;;
		stacked)
			i3-msg layout stacked
			;;
		split)
			i3-msg layout toggle split
			;;

	esac
}

options_open() {
    echo "open" > /tmp/polybar_side_panel_state
    ID_BAR=$(cat $WINDOW_ID_OPTIONS)
    launcher.sh &
}

options_close() {
    echo "close" > /tmp/polybar_side_panel_state
}

options_toggle() {
    if [ "$(cat /tmp/polybar_side_panel_state)" == "open" ]; then
        options_close
    else
        options_open
    fi
}

case "$1" in
    rofi)
        rofi_open;;
    search)
        search_open;;
    options)
        options_toggle;;
    launch)
        launch;;
    hide)
        echo "cmd:hide" >> /tmp/polybar_mqueue_top;;
    show)
        echo "cmd:show" >> /tmp/polybar_mqueue_top;;
esac
